export const permissions = {
  usersRead: 'users.read',
  usersUpdate: 'users.update',
  usersDisable: 'users.disable',
  placesRead: 'places.read',
  placesWrite: 'places.write',
  placesDelete: 'places.delete',
  categoriesRead: 'categories.read',
  communityRead: 'community.read',
  communityModerate: 'community.moderate',
  reviewsRead: 'reviews.read',
  reviewsModerate: 'reviews.moderate',
  walletRead: 'wallet.read',
  walletRecharge: 'wallet.recharge',
  storeRead: 'store.read',
  manageAdmins: 'admin.manage_admins',
} as const
