export const permissions = {
  usersRead: 'users.read',
  usersUpdate: 'users.update',
  usersDisable: 'users.disable',
  placesRead: 'places.read',
  placesWrite: 'places.write',
  placesDelete: 'places.delete',
  categoriesRead: 'categories.read',
  categoriesWrite: 'categories.write',
  categoriesDelete: 'categories.delete',
  communityRead: 'community.read',
  communityModerate: 'community.moderate',
  reviewsRead: 'reviews.read',
  reviewsModerate: 'reviews.moderate',
  notificationsRead: 'notifications.read',
  notificationsSend: 'notifications.send',
  contributionsRead: 'contributions.read',
  contributionsApprove: 'contributions.approve',
  contributionsReject: 'contributions.reject',
  pointsManage: 'points.manage',
  walletRead: 'wallet.read',
  walletRecharge: 'wallet.recharge',
  storeRead: 'store.read',
  storeWrite: 'store.write',
  storeDelete: 'store.delete',
  manageAdmins: 'admin.manage_admins',
} as const
