"""A generic, single database migration script.

Revision ID: 16e6d2c732aa
Revises: '0085d26d3b57'
Create Date: 2026-08-09 01:22:56.385368
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '16e6d2c732aa'
down_revision = '0085d26d3b57'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.add_column('users', sa.Column('location_source', sa.String(length=20), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.execute('CREATE INDEX IF NOT EXISTS idx_users_location ON users USING GIST (location)')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index('idx_users_location', table_name='users', postgresql_using='gist')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'location_source')
    op.drop_column('users', 'location')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'avatar_id')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


