"""A generic, single database migration script.

Revision ID: 3f754f995de2
Revises: 'b0c31b1f70b2'
Create Date: 2026-08-21 16:02:23.225183
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f754f995de2'
down_revision = 'b0c31b1f70b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_point_transactions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('CONTRIBUTION', 'TASK_REWARD', 'ACHIEVEMENT', 'GIFT', 'PENALTY', 'ADJUSTMENT', 'ADMIN_ADJUSTMENT', name='user_point_transaction_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REVOKED', name='user_point_transaction_status'), server_default='CONFIRMED', nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('extra_data', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_point_transactions_created_at'), 'user_point_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_point_transactions_reference_id'), 'user_point_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_user_point_transactions_reference_type'), 'user_point_transactions', ['reference_type'], unique=False)
    op.create_index(op.f('ix_user_point_transactions_status'), 'user_point_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_user_point_transactions_type'), 'user_point_transactions', ['type'], unique=False)
    op.create_index(op.f('ix_user_point_transactions_user_id'), 'user_point_transactions', ['user_id'], unique=False)
    op.create_table('place_contributions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('CREATE_PLACE', 'UPDATE_PLACE', 'ADD_IMAGE', 'UPDATE_INFORMATION', 'VERIFY_PLACE', name='place_contribution_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='place_contribution_status'), server_default='PENDING', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('points_awarded', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_contributions_created_at'), 'place_contributions', ['created_at'], unique=False)
    op.create_index(op.f('ix_place_contributions_place_id'), 'place_contributions', ['place_id'], unique=False)
    op.create_index(op.f('ix_place_contributions_reviewed_by'), 'place_contributions', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_place_contributions_status'), 'place_contributions', ['status'], unique=False)
    op.create_index(op.f('ix_place_contributions_type'), 'place_contributions', ['type'], unique=False)
    op.create_index(op.f('ix_place_contributions_user_id'), 'place_contributions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_contributions_user_id'), table_name='place_contributions')
    op.drop_index(op.f('ix_place_contributions_type'), table_name='place_contributions')
    op.drop_index(op.f('ix_place_contributions_status'), table_name='place_contributions')
    op.drop_index(op.f('ix_place_contributions_reviewed_by'), table_name='place_contributions')
    op.drop_index(op.f('ix_place_contributions_place_id'), table_name='place_contributions')
    op.drop_index(op.f('ix_place_contributions_created_at'), table_name='place_contributions')
    op.drop_table('place_contributions')
    op.drop_index(op.f('ix_user_point_transactions_user_id'), table_name='user_point_transactions')
    op.drop_index(op.f('ix_user_point_transactions_type'), table_name='user_point_transactions')
    op.drop_index(op.f('ix_user_point_transactions_status'), table_name='user_point_transactions')
    op.drop_index(op.f('ix_user_point_transactions_reference_type'), table_name='user_point_transactions')
    op.drop_index(op.f('ix_user_point_transactions_reference_id'), table_name='user_point_transactions')
    op.drop_index(op.f('ix_user_point_transactions_created_at'), table_name='user_point_transactions')
    op.drop_table('user_point_transactions')
    # ### end Alembic commands ###
