"""Pydantic schemas for user devices."""

from datetime import datetime
from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Field, field_validator


class DeviceRegisterRequest(BaseModel):
    """Request body for registering or updating a user device / FCM token."""

    device_id: str = Field(
        min_length=1,
        max_length=255,
        description="Unique identifier for the device (generated by the client).",
    )
    fcm_token: str = Field(
        min_length=1,
        max_length=512,
        description="Firebase Cloud Messaging registration token.",
    )
    platform: str = Field(
        min_length=3,
        max_length=10,
        description="Platform: 'android' or 'ios'.",
    )

    @field_validator("platform")
    @classmethod
    def validate_platform(cls, v: str) -> str:
        """Normalize platform to lowercase and validate."""
        lowered = v.strip().lower()
        if lowered not in ("android", "ios"):
            raise ValueError("Platform must be 'android' or 'ios'")
        return lowered


class DeviceRead(BaseModel):
    """Public device info returned to the user — FCM token is never exposed."""

    id: UUID
    device_id: str
    platform: str
    is_active: bool
    created_at: datetime

    model_config = {
        "from_attributes": True,
    }


class DeviceListResponse(BaseModel):
    """Wrapper for listing a user's devices."""

    devices: list[DeviceRead]
